[package]
name = "sqlite-broker"
version.workspace = true
edition = "2021"
description = "One SQLite file for many processes"
license.workspace = true
repository.workspace = true

[[bin]]
name = "sqlite-broker"
path = "src/main.rs"

[dependencies]
rusqlite = "0.32"
sqlite-broker-proto = { path = "../protocol" }
