[package]
name = "sqlite-broker-shim"
version.workspace = true
edition = "2021"
description = "LD_PRELOAD shim that forwards sqlite3_open to sqlite-broker"
license.workspace = true
repository.workspace = true

[lib]
name = "sqlite_broker"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
sqlite-broker-proto = { path = "../protocol" }
